### ISSUE TITLE
Why is the IPostmarkClient interface missing?

### ISSUE THREAD

**Issue by kfrancis** [wildbit/postmark-dotnet#20]
What's the reason for removing the interface? It was much more graceful to use in situations where DI is being used.

**Comment by atheken** [comment]
Hi @kfrancis It is still possible to isolate your tests from the Postmark API using the Postmark Client, but it's done in a slightly different way.

First, let me quickly explain the reasoning for the change: 

Since the client itself has some behavior (fixing/normalizing parameters, etc.), mocking it using an interface can lead to inconsistencies between how the tests behave using the a mock implementation vs. how the concrete client behaves. In addition, as we add more end points, there's the risk of the interface getting out of sync with the concrete implementation (and, depending on how you implement your mock, additional work each time the interface is extended).

If you have access to an 'http replay' server, you can use all of the concrete code, but only need to modify the base url when you construct your clients (here's one example in node, but I am sure many others are available: https://github.com/assaf/node-replay).

A more robust way that your tests can be isolated from the live API is by setting the [ClientFactory](https://github.com/wildbit/postmark-dotnet/blob/master/src/Postmark.PCL/PostmarkClientBase.cs#L28) on PostmarkClientBase. Combining this with your own fake [ISimpleHttpClient](https://github.com/wildbit/postmark-dotnet/blob/master/src/Postmark.PCL/ISimpleHttpClient.cs) will allow you to achieve the same level of isolation as a Client mock.

A way to get this working without a replay server would be to have two implementations of `ISimpleHttpClient` that you can swap out in your tests, `ProxiedRecorderSimpleHttpClient` and `PlaybackSimpleHttpClient` or similar. In the `ProxiedRecorderSimpleHttpClient`, the client would pass requests and responses to/from the live API, but serialize each to a file. Then, using `PlaybackSimpleHttpClient`, those serialized requests/responses may be played back when requests with the same attributes are sent in. This is more work to configure initially, but ensures that the responses your mock client provides are exactly the same as what you'd get from the real API.

*However*, it is understood that this may require additional modifications to your tests, and is relatively simple for us to add back in.

**Comment by kfrancis** [comment]
I wasn't using the interface to mock the function of mailing itself, I'm mocking it to satisfy dependencies for unit and functional testing of other parts of our ecosystem. It would be nice to see it included, but I can deal with it for now either until you add it back in or alternatively I can fork, add, and send a pull request (which I also don't mind).

**Comment by darrenshrwd** [comment]
It is handy to have an interface during development to redirect emails to https://mailtrap.io

**Comment by darrenshrwd** [comment]
I would like to use an interface to redirect emails to https://mailtrap.io during development. If I was to intercept these via ISimpleHttpClient I would then have to interpret your HttpRequestMessage to construct an SMTP to send to mailtrap rather than the simple PostmarkMessage.

Perhaps just do a IPostMark**Sending**Client, I only care about these two:

Task<PostmarkResponse> SendMessageAsync(PostmarkMessage message);
Task<IEnumerable<PostmarkResponse>> SendMessagesAsync(params PostmarkMessage[] messages);

**Comment by saasen** [comment]
> Since the client itself has some behavior (fixing/normalizing parameters, etc.), mocking it using an interface can lead to inconsistencies between how the tests behave using a mock implementation vs. how the concrete client behaves. In addition, as we add more endpoints, there's the risk of the interface getting out of sync with the concrete implementation (and, depending on how you implement your mock, additional work each time the interface is extended).

I don't agree fully on this.
I agree that when mocking the behavior might differ. I think that is something that's a given when mocking any class which communicates over the wire or something similar.

Sometimes you want to test a unit in itself, i.e. the business process. At least in our tests, we want to check if all the correct code is called. Using an `interface` or at least `virtual` methods would enable mocking frameworks (as they usually proxy class your own code) to be used more easily.

Another solution would be to create a wrapper class to make the method you need to mock `virtual` and just call the `base` method like this example:

```csharp
public class TestablePostmarkClient : PostmarkClient
{
    public TestablePostmarkClient(string token) : base(token) { }

    public new virtual async Task SendMessageAsync(PostmarkMessage message)
    {
        await base.SendMessageAsync(message);
    }
}
```

@atheken: I'm not really sure if understand your robust proposed solution to this. Could you provide a simple code sample for making this work without the replay server?

**Comment by kfrancis** [comment]
@saasen That works for my use case, thanks.
