### ISSUE TITLE
Legacy Extensions Still Use WaitForResult

### ISSUE THREAD

**Issue by kfrancis** [wildbit/postmark-dotnet#21]
Hello,

I'm having a crazy time trying to migrate from an older version (1.6) to 2.0.72. Nothing seems to work at all. Following the directions to make the change simply by including `using PostmarkDotNet.Legacy;` doesn't allow it to work. It appears that the legacy extension still uses WaitForResult.

Even calling `client.SendMessageAsync(message).Result` doesn't work - the app just infinitely hangs doing nothing (it seems). Any ideas?

**Comment by atheken** [comment]
Is this in a WinForms/WPF app?

**Comment by kfrancis** [comment]
WebForms

**Comment by ludogoarin** [comment]
Having same issue in MVC web app

**Comment by kfrancis** [comment]
So, essentially the issue is [this](http://stackoverflow.com/a/25589917/276461) - that you're providing an Async API but it's causing a deadlock when used from ASP.NET (any use really, WebForm/MVC/WebAPI/etc) as you need to use `.ConfigureAwait(false)` to stop it from deadlocking.

Basically, the only necessary change is in `ProcessRequestAsync`, to append `ConfigureAwait(false)`:

    protected async Task<TResponse> ProcessRequestAsync<TRequestBody, TResponse>(string apiPath,
            HttpMethod verb, TRequestBody message = null) where TRequestBody : class
        {
            // ....
            var result = await client.SendAsync(request).ConfigureAwait(false);
            var body = await result.Content.ReadAsStringAsync().ConfigureAwait(false);
         }
I've just forked and tested that change, and while I can't get _all_ tests to run (selenium related ones, and anything with windows phone) - the normal tests still continue to work. I'll send a pull request and if you could test and roll the change out to nuget so I can move forward on my blocked deploy - I would _super_ appreciate it :)

**Comment by atheken** [comment]
The issue with using `.ConfigureAwait(false)` is that it doesn't respect `SynchronizationContext`, and could (will?) run the task on another thread. This may work for some circumstances, but if a person's code relies on the task result to do something interesting with `HttpContext.Current` later on, I think this will result in an even worse set of issues and break the normal way that `async/await` is expected to work when using the the language features. The issue is specifically related to how SynchronizationContext is handled in `WaitForResult()` which we should probably remove, or reorganize to work properly when a synchronization context exists.

**Comment by kfrancis** [comment]
Another option @ludogoarin is to run the call within a task, so that the TPL can't get (and deadlock) the important thread, like this (from [here](http://blogs.msdn.com/b/pfxteam/archive/2012/04/13/10293638.aspx)):

    var response = Task.Run(() => client.SendMessageAsync(message)).Result;

While the fix I proposed above will correct the issue - it looks like it still requires that the actual page be run as async (so, use an `AsyncController` for MVC, specify Async="true" and use `Page.RegisterAsyncTask` for WebForms), and doesn't work for sync pages unless:

1. A proper sync API is also exposed (different from running the async methods in a sync way)
2. You use the trick above

**Comment by atheken** [comment]
@kfrancis I was toying with your latest `Task.Run` suggestion, but applying it in the WaitForResult method. I haven't had a chance to check it.

**Comment by kfrancis** [comment]
Hmm, @atheken, true. I guess it just needs a way to be more "universal" so that the simple lines still work in the various scenarios. The `Task.Run` workaround works for skipping the marshall to SynchronizationContext because it can't be found - but .. it's a work around, not likely a good solution.

**Comment by atheken** [comment]
@kfrancis I'm waiting for CI to finish and we'll cut a new release which fixes the synchronization issue (I think). Thanks for working with me on it, and the suggestion for `Task.Run`, which does resolve the issue entirely and obviates the need for `WaitForResult()` method.

**Comment by atheken** [comment]
Just an FYI, the NuGet packages (version 2.0.76) should now have this resolved. Please let us know if this resolves the threading issues you've reported @kfrancis and @ludogoarin.

**Comment by kfrancis** [comment]
Looks good to me @atheken!

**Comment by vinaykapadia** [comment]
@kfrancis Thank you SOOOO much! I was trying to use the Azure Active Directory Graph API to check if a User belongs to a certain Group. The problem was I had to do this in my Controller's OnAuthorization method, which was an override so I couldn't make it an async Task, it had to be void. Using `CurrentUser.CheckMemberGroupsAsync(groupList).Result` would just hang indefinitely (deadlock). I changed it to `Task.Run(() => CurrentUser.CheckMemberGroupsAsync(groupList)).Result` and it works great! You just solved hours and hours of trying to figure this thing out! Thanks again!
