### ISSUE TITLE
Please stop the annoying browser window open when Postmark is installed

### ISSUE THREAD

**Issue by benjamingr** [wildbit/postmark-dotnet#32]
I've seen it literally a thousand times now. It would be great if it would be more clever and not show it ever time I install Postmark.

**Comment by artfulhacker** [comment]
it was driving us so crazy we wrote our own SDK and stopped using this, also this was first reported here: #25 with no fix.

**Comment by atheken** [comment]
The notes were due to the fact that we released changes that needed to be conveyed to users adopting version 2.x vs 1.x. 

**I've removed the init.ps1, which loads these notes** (init.ps1 is run when the package is installed the first time, *but also, unfortunately,* also runs if you have the Package Management Console open when the Solution is loaded).

**Comment by benjamingr** [comment]
Thanks again (already commented on the other issue). I think Newtonsoft.Json somehow gets to show it only when you install it for the first time but not on package restore/when the console is open.

**Comment by artfulhacker** [comment]
very true, maybe take look at what he did, looks like it reads the package console

https://github.com/JamesNK/Newtonsoft.Json/blob/master/Build/install.ps1

:-)

**Comment by atheken** [comment]
I have also seen (and liked) [Glimpse's](https://github.com/glimpse) release notes. Part of the issue here is that "init.ps1" is overloaded by NuGet. So I kinda would like to see if we can get better support for this upstream (especially since Powershell is not the only console where NuGet packages are being installed these days...) Anyway, thanks for piping up about it.
