### ISSUE TITLE
Attachment Content is missing from JSON Webhook

### ISSUE THREAD

**Issue by arielsrv** [wildbit/postmark-dotnet#87]
I tried in various ways but the field never comes 

![image](https://user-images.githubusercontent.com/760657/87098471-bd0ff080-c21d-11ea-9b38-cdfc15331b29.png)ç

btw, in raw message exists for another example ....

![image](https://user-images.githubusercontent.com/760657/87098932-d6fe0300-c21e-11ea-9108-8467c89072f3.png)

**Comment by vladsandu** [comment]
@arielsrv sorry for the delay in getting to this issue. I just tested the inbound webhook and I am not able to reproduce this - I am getting the attachment content under `Attachment.Content` field as expected, having tested with multiple types of attachments including `application/pdf`.

Since you are posting this issue under the `postmark-dotnet` library, I am assuming you are trying to deserialize the webhook payload via a model present in the library. If so, please make sure you are using `PostmarkDotNet.PostmarkInboundMessage` model specifically designed for representing an inbound message post. The `Attachment.Content` field is present there.

Please let me know if you are still encountering this issue.

**Comment by vladsandu** [comment]
I’m closing this issue because it has been inactive for a few months and is currently not reproducible in the latest version of the library.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/wildbit/postmark-dotnet/releases).

Thank you!
